export const ProgramStudy = {
  data: [
    {
      id: "74234",
      program_study: "Hukum Ekonomi Syari'ah",
      faculty: "Fakultas Agama Islam",
      title: "Sarjana Hukum (S.H.)",
      accreditation: "Unggul",
      accreditation_number: "Data tidak tersedia",
      accreditation_date: "22/12/2021",
      dean: {
        name: "Dr. Mohamad Ali, S.Ag., M.Pd.",
        nidn: "0628117301",
      },
    },
    {
      id: "76231",
      program_study: "Ilmu Al-Quran dan Tafsir",
      faculty: "Fakultas Agama Islam",
      title: "Sarjana Agama (S.Ag.)",
      accreditation: "B",
      accreditation_number: "Data tidak tersedia",
      accreditation_date: "27/01/2022",
      dean: {
        name: "Dr. Mohamad Ali, S.Ag., M.Pd.",
        nidn: "0628117301",
      },
    },
    {
      id: "86208",
      program_study: "Pendidikan Agama Islam (S1)",
      faculty: "Fakultas Agama Islam",
      title: "Sarjana Pendidikan (S.Pd.)",
      accreditation: "Unggul",
      accreditation_number: "Data tidak tersedia",
      accreditation_date: "23/02/2022",
      dean: {
        name: "Dr. Mohamad Ali, S.Ag., M.Pd.",
        nidn: "0628117301",
      },
    },
    {
      id: "74105",
      program_study: "Hukum Ekonomi Syari'ah (S2)",
      faculty: "Fakultas Agama Islam",
      title: "Magister Hukum (M.H.)",
      accreditation: "Data tidak tersedia",
      accreditation_number: "Data tidak tersedia",
      accreditation_date: "Data tidak tersedia",
      dean: {
        name: "Dr. Mohamad Ali, S.Ag., M.Pd.",
        nidn: "0628117301",
      },
    },
    {
      id: "86108",
      program_study: "Pendidikan Agama Islam (S2)",
      faculty: "Fakultas Agama Islam",
      title: "Magister Pendidikan (M.Pd.)",
      accreditation: "Data tidak tersedia",
      accreditation_number: "Data tidak tersedia",
      accreditation_date: "Data tidak tersedia",
      dean: {
        name: "Dr. Mohamad Ali, S.Ag., M.Pd.",
        nidn: "0628117301",
      },
    },
    {
      id: "86030",
      program_study: "Pendidikan Agama Islam (S3)",
      faculty: "Fakultas Agama Islam",
      title: "Doktor (Dr.)",
      accreditation: "Data tidak tersedia",
      accreditation_number: "Data tidak tersedia",
      accreditation_date: "Data tidak tersedia",
      dean: {
        name: "Dr. Mohamad Ali, S.Ag., M.Pd.",
        nidn: "0628117301",
      },
    },
    {
      id: "62201",
      program_study: "Akuntansi (S1)",
      faculty: "Fakultas Ekonomi dan Bisnis",
      title: "Sarjana Akuntansi (S.Akt.)",
      accreditation: "Unggul",
      accreditation_number: "Data tidak tersedia",
      accreditation_date: "03/05/2024",
      dean: {
        name: "Prof. Dr. Muzakar Isa, S.E., M.Si.",
        nidn: "0605027502",
      },
    },
    {
      id: "61201",
      program_study: "Manajemen (S1)",
      faculty: "Fakultas Ekonomi dan Bisnis",
      title: "Sarjana Manajemen (S.M.)",
      accreditation: "Unggul",
      accreditation_number: "Data tidak tersedia",
      accreditation_date: "09/08/2024",
      dean: {
        name: "Prof. Dr. Muzakar Isa, S.E., M.Si.",
        nidn: "0605027502",
      },
    },
    {
      id: "60201",
      program_study: "Ekonomi Pembangunan",
      faculty: "Fakultas Ekonomi dan Bisnis",
      title: "Sarjana Ekonomi (S.E.)",
      accreditation: "Unggul",
      accreditation_number: "Data tidak tersedia",
      accreditation_date: "10/02/2023",
      dean: {
        name: "Prof. Dr. Muzakar Isa, S.E., M.Si.",
        nidn: "0605027502",
      },
    },
    {
      id: "61209",
      program_study: "Bisnis Digital",
      faculty: "Fakultas Ekonomi dan Bisnis",
      title: "Sarjana Bisnis Digital (S.BD.)",
      accreditation: "Baik",
      accreditation_number: "Data tidak tersedia",
      accreditation_date: "21/06/2024",
      dean: {
        name: "Prof. Dr. Muzakar Isa, S.E., M.Si.",
        nidn: "0605027502",
      },
    },
    {
      id: "62101",
      program_study: "Akuntansi (S2)",
      faculty: "Fakultas Ekonomi dan Bisnis",
      title: "Magister Akuntansi (M.Akt.)",
      accreditation: "B",
      accreditation_number: "Data tidak tersedia",
      accreditation_date: "Data lama",
      dean: {
        name: "Prof. Dr. Muzakar Isa, S.E., M.Si.",
        nidn: "0605027502",
      },
    },
    {
      id: "61101",
      program_study: "Manajemen (S2)",
      faculty: "Fakultas Ekonomi dan Bisnis",
      title: "Magister Manajemen (M.M.)",
      accreditation: "Unggul",
      accreditation_number: "Data tidak tersedia",
      accreditation_date: "25/11/2024",
      dean: {
        name: "Prof. Dr. Muzakar Isa, S.E., M.Si.",
        nidn: "0605027502",
      },
    },
    {
      id: "61004",
      program_study: "Ilmu Manajemen",
      faculty: "Fakultas Ekonomi dan Bisnis",
      title: "Doktor (Dr.)",
      accreditation: "Data tidak tersedia",
      accreditation_number: "Data tidak tersedia",
      accreditation_date: "Data tidak tersedia",
      dean: {
        name: "Prof. Dr. Muzakar Isa, S.E., M.Si.",
        nidn: "0605027502",
      },
    },
    {
      id: "48201",
      program_study: "Farmasi (S1)",
      faculty: "Fakultas Farmasi",
      title: "Sarjana Farmasi (S.Farm.)",
      accreditation: "Unggul",
      accreditation_number: "Data tidak tersedia",
      accreditation_date: "26/08/2022",
      dean: {
        name: "Prof. Erindyah Retno Wikantyasning, M.Si., S.Si., Ph.D.",
        nidn: "0613027401",
      },
    },
    {
      id: "48901",
      program_study: "Apoteker",
      faculty: "Fakultas Farmasi",
      title: "Apoteker (apt.)",
      accreditation: "Unggul",
      accreditation_number: "Data tidak tersedia",
      accreditation_date: "26/08/2022",
      dean: {
        name: "Prof. Erindyah Retno Wikantyasning, M.Si., S.Si., Ph.D.",
        nidn: "0613027401",
      },
    },
    {
      id: "48101",
      program_study: "Farmasi (S2)",
      faculty: "Fakultas Farmasi",
      title: "Magister Farmasi (M.Farm.)",
      accreditation: "Data tidak tersedia",
      accreditation_number: "Data tidak tersedia",
      accreditation_date: "Data tidak tersedia",
      dean: {
        name: "Prof. Erindyah Retno Wikantyasning, M.Si., S.Si., Ph.D.",
        nidn: "0613027401",
      },
    },
    {
      id: "48001",
      program_study: "Farmasi (S3)",
      faculty: "Fakultas Farmasi",
      title: "Doktor (Dr.)",
      accreditation: "Data tidak tersedia",
      accreditation_number: "Data tidak tersedia",
      accreditation_date: "Data tidak tersedia",
      dean: {
        name: "Prof. Erindyah Retno Wikantyasning, M.Si., S.Si., Ph.D.",
        nidn: "0613027401",
      },
    },
    {
      id: "51201",
      program_study: "Geografi",
      faculty: "Fakultas Geografi",
      title: "Sarjana Sains (S.Si.)",
      accreditation: "Unggul",
      accreditation_number: "Data tidak tersedia",
      accreditation_date: "24/06/2024",
      dean: {
        name: "Jumadi, S.Si., M.Sc, Ph.D.",
        nidn: "Data tidak tersedia",
      },
    },
    {
      id: "51202",
      program_study: "Sains Informasi Geografi",
      faculty: "Fakultas Geografi",
      title: "Sarjana Sains (S.Si.)",
      accreditation: "Baik",
      accreditation_number: "Data tidak tersedia",
      accreditation_date: "17/09/2024",
      dean: {
        name: "Jumadi, S.Si., M.Sc, Ph.D.",
        nidn: "Data tidak tersedia",
      },
    },
    {
      id: "74201",
      program_study: "Ilmu Hukum (S1)",
      faculty: "Fakultas Hukum dan Ilmu Politik",
      title: "Sarjana Hukum (S.H.)",
      accreditation: "Unggul",
      accreditation_number: "Data tidak tersedia",
      accreditation_date: "03/10/2024",
      dean: {
        name: "Prof. Dr. Kelik Wardiono, S.H., M.H.",
        nidn: "0026126801",
      },
    },
    {
      id: "63203",
      program_study: "Administrasi Publik",
      faculty: "Fakultas Hukum dan Ilmu Politik",
      title: "Data tidak tersedia",
      accreditation: "Data tidak tersedia",
      accreditation_number: "Data tidak tersedia",
      accreditation_date: "Data tidak tersedia",
      dean: {
        name: "Prof. Dr. Kelik Wardiono, S.H., M.H.",
        nidn: "0026126801",
      },
    },
    {
      id: "64201",
      program_study: "Hubungan Internasional",
      faculty: "Fakultas Hukum dan Ilmu Politik",
      title: "Data tidak tersedia",
      accreditation: "Data tidak tersedia",
      accreditation_number: "Data tidak tersedia",
      accreditation_date: "Data tidak tersedia",
      dean: {
        name: "Prof. Dr. Kelik Wardiono, S.H., M.H.",
        nidn: "0026126801",
      },
    },
    {
      id: "74101",
      program_study: "Ilmu Hukum (S2)",
      faculty: "Fakultas Hukum dan Ilmu Politik",
      title: "Magister Hukum (M.H.)",
      accreditation: "Data tidak tersedia",
      accreditation_number: "Data tidak tersedia",
      accreditation_date: "Data tidak tersedia",
      dean: {
        name: "Prof. Dr. Kelik Wardiono, S.H., M.H.",
        nidn: "0026126801",
      },
    },
    {
      id: "74001",
      program_study: "Ilmu Hukum (S3)",
      faculty: "Fakultas Hukum dan Ilmu Politik",
      title: "Doktor (Dr.)",
      accreditation: "Data tidak tersedia",
      accreditation_number: "Data tidak tersedia",
      accreditation_date: "Data tidak tersedia",
      dean: {
        name: "Prof. Dr. Kelik Wardiono, S.H., M.H.",
        nidn: "0026126801",
      },
    },
    {
      id: "11202",
      program_study: "Fisioterapi (S1)",
      faculty: "Fakultas Ilmu Kesehatan",
      title: "Sarjana Fisioterapi (S.Fis.)",
      accreditation: "Unggul",
      accreditation_number: "Data tidak tersedia",
      accreditation_date: "25/08/2023",
      dean: {
        name: "Dr. Umi Budi Rahayu S.Fis., Ftr., M.Kes.",
        nidn: "Data tidak tersedia",
      },
    },
    {
      id: "13211",
      program_study: "Ilmu Gizi",
      faculty: "Fakultas Ilmu Kesehatan",
      title: "Sarjana Gizi (S.Gz.)",
      accreditation: "Unggul",
      accreditation_number: "Data tidak tersedia",
      accreditation_date: "30/12/2024",
      dean: {
        name: "Dr. Umi Budi Rahayu S.Fis., Ftr., M.Kes.",
        nidn: "Data tidak tersedia",
      },
    },
    {
      id: "14201",
      program_study: "Keperawatan (S1)",
      faculty: "Fakultas Ilmu Kesehatan",
      title: "Sarjana Keperawatan (S.Kep.)",
      accreditation: "Unggul",
      accreditation_number: "Data tidak tersedia",
      accreditation_date: "24/06/2021",
      dean: {
        name: "Dr. Umi Budi Rahayu S.Fis., Ftr., M.Kes.",
        nidn: "Data tidak tersedia",
      },
    },
    {
      id: "13201",
      program_study: "Kesehatan Masyarakat",
      faculty: "Fakultas Ilmu Kesehatan",
      title: "Sarjana Kesehatan Masyarakat (S.K.M.)",
      accreditation: "Unggul",
      accreditation_number: "Data tidak tersedia",
      accreditation_date: "28/06/2024",
      dean: {
        name: "Dr. Umi Budi Rahayu S.Fis., Ftr., M.Kes.",
        nidn: "Data tidak tersedia",
      },
    },
    {
      id: "13912",
      program_study: "Dietisien",
      faculty: "Fakultas Ilmu Kesehatan",
      title: "Dietisien",
      accreditation: "Baik",
      accreditation_number: "Data tidak tersedia",
      accreditation_date: "20/08/2024",
      dean: {
        name: "Dr. Umi Budi Rahayu S.Fis., Ftr., M.Kes.",
        nidn: "Data tidak tersedia",
      },
    },
    {
      id: "11902",
      program_study: "Fisioterapi (Profesi)",
      faculty: "Fakultas Ilmu Kesehatan",
      title: "Fisioterapis (Ftr.)",
      accreditation: "Unggul",
      accreditation_number: "Data tidak tersedia",
      accreditation_date: "25/08/2023",
      dean: {
        name: "Dr. Umi Budi Rahayu S.Fis., Ftr., M.Kes.",
        nidn: "Data tidak tersedia",
      },
    },
    {
      id: "14901",
      program_study: "Ners",
      faculty: "Fakultas Ilmu Kesehatan",
      title: "Ners (Ners)",
      accreditation: "Unggul",
      accreditation_number: "Data tidak tersedia",
      accreditation_date: "24/06/2021",
      dean: {
        name: "Dr. Umi Budi Rahayu S.Fis., Ftr., M.Kes.",
        nidn: "Data tidak tersedia",
      },
    },
    {
      id: "14101",
      program_study: "Keperawatan (S2)",
      faculty: "Fakultas Ilmu Kesehatan",
      title: "Magister Keperawatan (M.Kep.)",
      accreditation: "Data tidak tersedia",
      accreditation_number: "Data tidak tersedia",
      accreditation_date: "Data tidak tersedia",
      dean: {
        name: "Dr. Umi Budi Rahayu S.Fis., Ftr., M.Kes.",
        nidn: "Data tidak tersedia",
      },
    },
    {
      id: "11201",
      program_study: "Kedokteran",
      faculty: "Fakultas Kedokteran",
      title: "Sarjana Kedokteran (S.Ked.)",
      accreditation: "Unggul",
      accreditation_number: "Data tidak tersedia",
      accreditation_date: "09/06/2023",
      dean: {
        name: "Dr. dr. Flora Ramona Sigit Prakoeswa, M.Kes, Sp.D.V.",
        nidn: "0605067202",
      },
    },
    {
      id: "11901",
      program_study: "Dokter",
      faculty: "Fakultas Kedokteran",
      title: "Dokter (dr.)",
      accreditation: "Unggul",
      accreditation_number: "Data tidak tersedia",
      accreditation_date: "09/06/2023",
      dean: {
        name: "Dr. dr. Flora Ramona Sigit Prakoeswa, M.Kes, Sp.D.V.",
        nidn: "0605067202",
      },
    },
    {
      id: "13161",
      program_study: "Administrasi Rumah Sakit",
      faculty: "Fakultas Kedokteran",
      title: "Magister Administrasi Rumah Sakit (M.ARS.)",
      accreditation: "Data tidak tersedia",
      accreditation_number: "Data tidak tersedia",
      accreditation_date: "Data tidak tersedia",
      dean: {
        name: "Dr. dr. Flora Ramona Sigit Prakoeswa, M.Kes, Sp.D.V.",
        nidn: "0605067202",
      },
    },
    {
      id: "12201",
      program_study: "Pendidikan Dokter Gigi",
      faculty: "Fakultas Kedokteran Gigi",
      title: "Sarjana Kedokteran Gigi (S.K.G.)",
      accreditation: "Unggul",
      accreditation_number: "Data tidak tersedia",
      accreditation_date: "18/04/2024",
      dean: {
        name: "drg. Noor Hafida Widyastuti, Sp.KG.",
        nidn: "0601938402",
      },
    },
    {
      id: "12901",
      program_study: "Dokter Gigi",
      faculty: "Fakultas Kedokteran Gigi",
      title: "Dokter Gigi (drg.)",
      accreditation: "Unggul",
      accreditation_number: "Data tidak tersedia",
      accreditation_date: "18/04/2024",
      dean: {
        name: "drg. Noor Hafida Widyastuti, Sp.KG.",
        nidn: "0601938402",
      },
    },
    {
      id: "87209",
      program_study: "Pendidikan Akuntansi",
      faculty: "Fakultas Keguruan dan Ilmu Pendidikan",
      title: "Sarjana Pendidikan (S.Pd.)",
      accreditation: "Unggul",
      accreditation_number: "Data tidak tersedia",
      accreditation_date: "06/09/2023",
      dean: {
        name: "Prof. Dr. Anam Sutopo, S.Pd., M.Hum.",
        nidn: "Data tidak tersedia",
      },
    },
    {
      id: "88203",
      program_study: "Pendidikan Bahasa Inggris (S1)",
      faculty: "Fakultas Keguruan dan Ilmu Pendidikan",
      title: "Sarjana Pendidikan (S.Pd.)",
      accreditation: "Unggul",
      accreditation_number: "Data tidak tersedia",
      accreditation_date: "27/09/2023",
      dean: {
        name: "Prof. Dr. Anam Sutopo, S.Pd., M.Hum.",
        nidn: "Data tidak tersedia",
      },
    },
    {
      id: "88201",
      program_study: "Pendidikan Bahasa dan Sastra Indonesia",
      faculty: "Fakultas Keguruan dan Ilmu Pendidikan",
      title: "Sarjana Pendidikan (S.Pd.)",
      accreditation: "Unggul",
      accreditation_number: "Data tidak tersedia",
      accreditation_date: "27/06/2023",
      dean: {
        name: "Prof. Dr. Anam Sutopo, S.Pd., M.Hum.",
        nidn: "Data tidak tersedia",
      },
    },
    {
      id: "84205",
      program_study: "Pendidikan Biologi",
      faculty: "Fakultas Keguruan dan Ilmu Pendidikan",
      title: "Sarjana Pendidikan (S.Pd.)",
      accreditation: "Unggul",
      accreditation_number: "Data tidak tersedia",
      accreditation_date: "18/04/2023",
      dean: {
        name: "Prof. Dr. Anam Sutopo, S.Pd., M.Hum.",
        nidn: "Data tidak tersedia",
      },
    },
    {
      id: "87202",
      program_study: "Pendidikan Geografi",
      faculty: "Fakultas Keguruan dan Ilmu Pendidikan",
      title: "Sarjana Pendidikan (S.Pd.)",
      accreditation: "Unggul",
      accreditation_number: "Data tidak tersedia",
      accreditation_date: "06/09/2023",
      dean: {
        name: "Prof. Dr. Anam Sutopo, S.Pd., M.Hum.",
        nidn: "Data tidak tersedia",
      },
    },
    {
      id: "86206",
      program_study: "Pendidikan Guru Sekolah Dasar (PGSD)",
      faculty: "Fakultas Keguruan dan Ilmu Pendidikan",
      title: "Sarjana Pendidikan (S.Pd.)",
      accreditation: "Unggul",
      accreditation_number: "Data tidak tersedia",
      accreditation_date: "05/03/2025",
      dean: {
        name: "Prof. Dr. Anam Sutopo, S.Pd., M.Hum.",
        nidn: "Data tidak tersedia",
      },
    },
    {
      id: "86207",
      program_study: "Pendidikan Guru Pendidikan Anak Usia Dini (PG-PAUD)",
      faculty: "Fakultas Keguruan dan Ilmu Pendidikan",
      title: "Sarjana Pendidikan (S.Pd.)",
      accreditation: "Data tidak tersedia",
      accreditation_number: "Data tidak tersedia",
      accreditation_date: "Data tidak tersedia",
      dean: {
        name: "Prof. Dr. Anam Sutopo, S.Pd., M.Hum.",
        nidn: "Data tidak tersedia",
      },
    },
    {
      id: "84202",
      program_study: "Pendidikan Matematika (S1)",
      faculty: "Fakultas Keguruan dan Ilmu Pendidikan",
      title: "Sarjana Pendidikan (S.Pd.)",
      accreditation: "Unggul",
      accreditation_number: "Data tidak tersedia",
      accreditation_date: "18/04/2023",
      dean: {
        name: "Prof. Dr. Anam Sutopo, S.Pd., M.Hum.",
        nidn: "Data tidak tersedia",
      },
    },
    {
      id: "83207",
      program_study: "Pendidikan Teknik Informatika",
      faculty: "Fakultas Keguruan dan Ilmu Pendidikan",
      title: "Sarjana Pendidikan (S.Pd.)",
      accreditation: "Data tidak tersedia",
      accreditation_number: "Data tidak tersedia",
      accreditation_date: "Data tidak tersedia",
      dean: {
        name: "Prof. Dr. Anam Sutopo, S.Pd., M.Hum.",
        nidn: "Data tidak tersedia",
      },
    },
    {
      id: "85207",
      program_study: "Pendidikan Jasmani",
      faculty: "Fakultas Keguruan dan Ilmu Pendidikan",
      title: "Sarjana Pendidikan (S.Pd.)",
      accreditation: "Unggul",
      accreditation_number: "Data tidak tersedia",
      accreditation_date: "04/03/2024",
      dean: {
        name: "Prof. Dr. Anam Sutopo, S.Pd., M.Hum.",
        nidn: "Data tidak tersedia",
      },
    },
    {
      id: "87205",
      program_study: "Pendidikan Pancasila dan Kewarganegaraan",
      faculty: "Fakultas Keguruan dan Ilmu Pendidikan",
      title: "Sarjana Pendidikan (S.Pd.)",
      accreditation: "Unggul",
      accreditation_number: "Data tidak tersedia",
      accreditation_date: "04/03/2024",
      dean: {
        name: "Prof. Dr. Anam Sutopo, S.Pd., M.Hum.",
        nidn: "Data tidak tersedia",
      },
    },
    {
      id: "86904",
      program_study: "Pendidikan Profesi Guru (PPG)",
      faculty: "Fakultas Keguruan dan Ilmu Pendidikan",
      title: "Guru (Gr.)",
      accreditation: "Data tidak tersedia",
      accreditation_number: "Data tidak tersedia",
      accreditation_date: "Data tidak tersedia",
      dean: {
        name: "Prof. Dr. Anam Sutopo, S.Pd., M.Hum.",
        nidn: "Data tidak tersedia",
      },
    },
    {
      id: "86104",
      program_study: "Administrasi Pendidikan",
      faculty: "Fakultas Keguruan dan Ilmu Pendidikan",
      title: "Magister Pendidikan (M.Pd.)",
      accreditation: "Data tidak tersedia",
      accreditation_number: "Data tidak tersedia",
      accreditation_date: "Data tidak tersedia",
      dean: {
        name: "Prof. Dr. Anam Sutopo, S.Pd., M.Hum.",
        nidn: "Data tidak tersedia",
      },
    },
    {
      id: "88101",
      program_study: "Pendidikan Bahasa Indonesia (S2)",
      faculty: "Fakultas Keguruan dan Ilmu Pendidikan",
      title: "Magister Pendidikan (M.Pd.)",
      accreditation: "Data tidak tersedia",
      accreditation_number: "Data tidak tersedia",
      accreditation_date: "Data tidak tersedia",
      dean: {
        name: "Prof. Dr. Anam Sutopo, S.Pd., M.Hum.",
        nidn: "Data tidak tersedia",
      },
    },
    {
      id: "88103",
      program_study: "Pendidikan Bahasa Inggris (S2)",
      faculty: "Fakultas Keguruan dan Ilmu Pendidikan",
      title: "Magister Pendidikan (M.Pd.)",
      accreditation: "Data tidak tersedia",
      accreditation_number: "Data tidak tersedia",
      accreditation_date: "Data tidak tersedia",
      dean: {
        name: "Prof. Dr. Anam Sutopo, S.Pd., M.Hum.",
        nidn: "Data tidak tersedia",
      },
    },
    {
      id: "86122",
      program_study: "Pendidikan Dasar",
      faculty: "Fakultas Keguruan dan Ilmu Pendidikan",
      title: "Magister Pendidikan (M.Pd.)",
      accreditation: "Data tidak tersedia",
      accreditation_number: "Data tidak tersedia",
      accreditation_date: "Data tidak tersedia",
      dean: {
        name: "Prof. Dr. Anam Sutopo, S.Pd., M.Hum.",
        nidn: "Data tidak tersedia",
      },
    },
    {
      id: "84102",
      program_study: "Pendidikan Matematika (S2)",
      faculty: "Fakultas Keguruan dan Ilmu Pendidikan",
      title: "Magister Pendidikan (M.Pd.)",
      accreditation: "Data tidak tersedia",
      accreditation_number: "Data tidak tersedia",
      accreditation_date: "Data tidak tersedia",
      dean: {
        name: "Prof. Dr. Anam Sutopo, S.Pd., M.Hum.",
        nidn: "Data tidak tersedia",
      },
    },
    {
      id: "86003",
      program_study: "Ilmu Pendidikan",
      faculty: "Fakultas Keguruan dan Ilmu Pendidikan",
      title: "Doktor (Dr.)",
      accreditation: "Data tidak tersedia",
      accreditation_number: "Data tidak tersedia",
      accreditation_date: "Data tidak tersedia",
      dean: {
        name: "Prof. Dr. Anam Sutopo, S.Pd., M.Hum.",
        nidn: "Data tidak tersedia",
      },
    },
    {
      id: "70201",
      program_study: "Ilmu Komunikasi",
      faculty: "Fakultas Komunikasi dan Informatika",
      title: "Sarjana Ilmu Komunikasi (S.I.Kom.)",
      accreditation: "Unggul",
      accreditation_number: "Data tidak tersedia",
      accreditation_date: "02/11/2021",
      dean: {
        name: "Dr. Endah Sudarmilah, S.T, M.Eng.",
        nidn: "0618017901",
      },
    },
    {
      id: "57201",
      program_study: "Sistem Informasi",
      faculty: "Fakultas Komunikasi dan Informatika",
      title: "Sarjana Komputer (S.Kom.)",
      accreditation: "Baik",
      accreditation_number: "Data tidak tersedia",
      accreditation_date: "Data lama",
      dean: {
        name: "Dr. Endah Sudarmilah, S.T, M.Eng.",
        nidn: "0618017901",
      },
    },
    {
      id: "55201",
      program_study: "Teknik Informatika",
      faculty: "Fakultas Komunikasi dan Informatika",
      title: "Sarjana Komputer (S.Kom.)",
      accreditation: "Unggul",
      accreditation_number: "Data tidak tersedia",
      accreditation_date: "24/03/2025",
      dean: {
        name: "Dr. Endah Sudarmilah, S.T, M.Eng.",
        nidn: "0618017901",
      },
    },
    {
      id: "55102",
      program_study: "Informatika (S2)",
      faculty: "Fakultas Komunikasi dan Informatika",
      title: "Magister Komputer (M.Kom.)",
      accreditation: "Data tidak tersedia",
      accreditation_number: "Data tidak tersedia",
      accreditation_date: "Data tidak tersedia",
      dean: {
        name: "Dr. Endah Sudarmilah, S.T, M.Eng.",
        nidn: "0618017901",
      },
    },
    {
      id: "73201",
      program_study: "Psikologi (S1)",
      faculty: "Fakultas Psikologi",
      title: "Sarjana Psikologi (S.Psi.)",
      accreditation: "Unggul",
      accreditation_number: "Data tidak tersedia",
      accreditation_date: "15/12/2021",
      dean: {
        name: "Dr. Lisnawati Ruhaena, S.Psi, M.Si., Psikolog.",
        nidn: "0616036901",
      },
    },
    {
      id: ["73901", "73902"],
      program_study: "Pendidikan Profesi Psikologi",
      faculty: "Fakultas Psikologi",
      title: "Psikolog",
      accreditation: "Data tidak tersedia",
      accreditation_number: "Data tidak tersedia",
      accreditation_date: "Data tidak tersedia",
      dean: {
        name: "Dr. Lisnawati Ruhaena, S.Psi, M.Si., Psikolog.",
        nidn: "0616036901",
      },
    },
    {
      id: "73101",
      program_study: "Psikologi (S2)",
      faculty: "Fakultas Psikologi",
      title: "Magister Psikologi (M.Psi.)",
      accreditation: "Data tidak tersedia",
      accreditation_number: "Data tidak tersedia",
      accreditation_date: "Data tidak tersedia",
      dean: {
        name: "Dr. Lisnawati Ruhaena, S.Psi, M.Si., Psikolog.",
        nidn: "0616036901",
      },
    },
    {
      id: "73001",
      program_study: "Psikologi (S3)",
      faculty: "Fakultas Psikologi",
      title: "Doktor (Dr.)",
      accreditation: "Data tidak tersedia",
      accreditation_number: "Data tidak tersedia",
      accreditation_date: "Data tidak tersedia",
      dean: {
        name: "Dr. Lisnawati Ruhaena, S.Psi, M.Si., Psikolog.",
        nidn: "0616036901",
      },
    },
    {
      id: "23201",
      program_study: "Arsitektur",
      faculty: "Fakultas Teknik",
      title: "Sarjana Arsitektur (S.Ars.)",
      accreditation: "Unggul",
      accreditation_number: "Data tidak tersedia",
      accreditation_date: "22/12/2021",
      dean: {
        name: "Prof. Ir. Mochamad Solikin, M.T., Ph.D.",
        nidn: "0617127201",
      },
    },
    {
      id: "20201",
      program_study: "Teknik Elektro",
      faculty: "Fakultas Teknik",
      title: "Sarjana Teknik (S.T.)",
      accreditation: "Unggul",
      accreditation_number: "Data tidak tersedia",
      accreditation_date: "19/10/2021",
      dean: {
        name: "Prof. Ir. Mochamad Solikin, M.T., Ph.D.",
        nidn: "0617127201",
      },
    },
    {
      id: "26201",
      program_study: "Teknik Industri",
      faculty: "Fakultas Teknik",
      title: "Sarjana Teknik (S.T.)",
      accreditation: "Unggul",
      accreditation_number: "Data tidak tersedia",
      accreditation_date: "21/04/2025",
      dean: {
        name: "Prof. Ir. Mochamad Solikin, M.T., Ph.D.",
        nidn: "0617127201",
      },
    },
    {
      id: "24201",
      program_study: "Teknik Kimia (S1)",
      faculty: "Fakultas Teknik",
      title: "Sarjana Teknik (S.T.)",
      accreditation: "Data tidak tersedia",
      accreditation_number: "Data tidak tersedia",
      accreditation_date: "Data tidak tersedia",
      dean: {
        name: "Prof. Ir. Mochamad Solikin, M.T., Ph.D.",
        nidn: "0617127201",
      },
    },
    {
      id: "21201",
      program_study: "Teknik Mesin (S1)",
      faculty: "Fakultas Teknik",
      title: "Sarjana Teknik (S.T.)",
      accreditation: "Unggul",
      accreditation_number: "Data tidak tersedia",
      accreditation_date: "Data lama",
      dean: {
        name: "Prof. Ir. Mochamad Solikin, M.T., Ph.D.",
        nidn: "0617127201",
      },
    },
    {
      id: "22201",
      program_study: "Teknik Sipil (S1)",
      faculty: "Fakultas Teknik",
      title: "Sarjana Teknik (S.T.)",
      accreditation: "Unggul",
      accreditation_number: "Data tidak tersedia",
      accreditation_date: "Data lama",
      dean: {
        name: "Prof. Ir. Mochamad Solikin, M.T., Ph.D.",
        nidn: "0617127201",
      },
    },
    {
      id: "23902",
      program_study: "Profesi Insinyur",
      faculty: "Fakultas Teknik",
      title: "Insinyur (Ir.)",
      accreditation: "Data tidak tersedia",
      accreditation_number: "Data tidak tersedia",
      accreditation_date: "Data tidak tersedia",
      dean: {
        name: "Prof. Ir. Mochamad Solikin, M.T., Ph.D.",
        nidn: "0617127201",
      },
    },
    {
      id: "24101",
      program_study: "Teknik Kimia (S2)",
      faculty: "Fakultas Teknik",
      title: "Magister Teknik (M.T.)",
      accreditation: "Data tidak tersedia",
      accreditation_number: "Data tidak tersedia",
      accreditation_date: "Data tidak tersedia",
      dean: {
        name: "Prof. Ir. Mochamad Solikin, M.T., Ph.D.",
        nidn: "0617127201",
      },
    },
    {
      id: "21101",
      program_study: "Teknik Mesin (S2)",
      faculty: "Fakultas Teknik",
      title: "Magister Teknik (M.T.)",
      accreditation: "Data tidak tersedia",
      accreditation_number: "Data tidak tersedia",
      accreditation_date: "Data tidak tersedia",
      dean: {
        name: "Prof. Ir. Mochamad Solikin, M.T., Ph.D.",
        nidn: "0617127201",
      },
    },
    {
      id: "22101",
      program_study: "Teknik Sipil (S2)",
      faculty: "Fakultas Teknik",
      title: "Magister Teknik (M.T.)",
      accreditation: "Data tidak tersedia",
      accreditation_number: "Data tidak tersedia",
      accreditation_date: "Data tidak tersedia",
      dean: {
        name: "Prof. Ir. Mochamad Solikin, M.T., Ph.D.",
        nidn: "0617127201",
      },
    },
    {
      id: "21002",
      program_study: "Teknik Mesin (S3)",
      faculty: "Fakultas Teknik",
      title: "Doktor (Dr.)",
      accreditation: "Data tidak tersedia",
      accreditation_number: "Data tidak tersedia",
      accreditation_date: "Data tidak tersedia",
      dean: {
        name: "Prof. Ir. Mochamad Solikin, M.T., Ph.D.",
        nidn: "0617127201",
      },
    },
  ],
};
